- name: Verify reserve_ip parameters
  block:
    - name: Check opnsense_reserve_ip_ip_addr is present
      fail:
        msg: opnsense_reserve_ip_ip_addr must be specified
      when: opnsense_reserve_ip_ip_addr is undefined

    - name: Check opnsense_reserve_ip_ip_addr is present
      fail:
        msg: opnsense_reserve_ip_ip_addr must be specified
      when: opnsense_reserve_ip_ip_addr is undefined

  when: opnsense_action == 'reserve_ip'
